### ISSUE TITLE
管理这里怎么配置的

### ISSUE THREAD

**Issue by GZ-Alinx** [o8oo8o/GoWebSSH#7]
管理这里 密码是多少 怎么配置的 ， 这块必须要完善，否则用户使用时无法进行区分权限 ，那么就只能是本地工具了 。   这样的工具最好能上线到内网所有人使用只有登录账号才能看到资源。  这样此工具将不再是工具了

**Comment by o8oo8o** [comment]
新版本已经支持登陆，多用户
